import Head from "next/head";
import { Inter } from "next/font/google";
import MainLayout from "@/concepts/layouts/MainLayout";
import PersonalAudioTourGuide from "@/concepts/layouts/PersonalAudioTourGuide";
import SecondBlock from "@/concepts/landing/SecondBlock";
import ImageBlock from "@/concepts/landing/ImageBlock";
const inter = Inter({ subsets: ["latin"] });
import MakeYourPhone from "@/concepts/layouts/MakeYourPhone";

export default function Home() {
  return (
    <>
      <Head>
        <title>Flat Planet</title>
        {/*<meta name="description" content="Generated by create next app" />*/}
        {/*<meta name="viewport" content="width=device-width, initial-scale=1" />*/}
        {/*<link rel="icon" href="/favicon.ico" />*/}
      </Head>
      <MainLayout>
        <PersonalAudioTourGuide />
        <SecondBlock />
        <ImageBlock />
        <MakeYourPhone/>
      </MainLayout>
    </>
  );
}
